# Generated by Django 3.2.7 on 2023-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('emotion', models.CharField(default='', max_length=20)),
                ('race', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.DateField()),
                ('video', models.FileField(upload_to='video')),
                ('processed_video', models.FileField(default='Na', upload_to='processed_video')),
            ],
        ),
    ]
