# Generated by Django 3.2.7 on 2023-03-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.DateField(default='NA'),
        ),
    ]
