# Generated by Django 3.2.7 on 2023-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_person_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_db',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
