# Generated by Django 3.2.7 on 2023-03-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_video2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
